import {
  boolean,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uuid,
  uniqueIndex,
} from "drizzle-orm/pg-core";

export const searchProfiles = pgTable("search_profiles", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: text("owner_id").notNull().default("primary"),
  name: text("name").notNull(),
  zip: text("zip").notNull(),
  radiusMiles: integer("radius_miles").notNull().default(100),
  make: text("make"),
  model: text("model"),
  trim: text("trim"),
  yearMin: integer("year_min"),
  yearMax: integer("year_max"),
  mileageMax: integer("mileage_max"),
  priceMin: numeric("price_min", { precision: 10, scale: 2 }),
  priceMax: numeric("price_max", { precision: 10, scale: 2 }),
  maxAskingRatio: numeric("max_asking_ratio", { precision: 5, scale: 4 }).notNull().default("0.7000"),
  requireCleanTitle: boolean("require_clean_title").notNull().default(true),
  allowedRepairCategories: jsonb("allowed_repair_categories").$type<string[]>().notNull().default([]),
  rejectedRepairCategories: jsonb("rejected_repair_categories").$type<string[]>().notNull().default([]),
  maxExpectedRepairs: numeric("max_expected_repairs", { precision: 10, scale: 2 }),
  minDealMargin: numeric("min_deal_margin", { precision: 10, scale: 2 }).notNull().default("2000"),
  maxFraudRiskScore: integer("max_fraud_risk_score").notNull().default(40),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const listings = pgTable("listings", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: text("owner_id").notNull().default("primary"),
  sourceId: text("source_id").notNull(),
  sourceKind: text("source_kind").notNull(),
  sourceListingId: text("source_listing_id"),
  url: text("url"),
  rawText: text("raw_text"),
  title: text("title"),
  description: text("description"),
  price: numeric("price", { precision: 10, scale: 2 }),
  priceHistory: jsonb("price_history").$type<Array<{ price: number; at: string; note?: string }>>().notNull().default([]),
  mileage: integer("mileage"),
  location: text("location"),
  vin: text("vin"),
  vinConfidence: text("vin_confidence").notNull().default("NONE"),
  vehicleYear: integer("vehicle_year"),
  vehicleMake: text("vehicle_make"),
  vehicleModel: text("vehicle_model"),
  vehicleTrim: text("vehicle_trim"),
  sellerName: text("seller_name"),
  sellerType: text("seller_type").notNull().default("unknown"),
  sellerContact: text("seller_contact"),
  photos: jsonb("photos").$type<Array<{ url?: string; note?: string; analyzedFindings?: string[] }>>().notNull().default([]),
  titleClaims: jsonb("title_claims").$type<Array<{ claim: string; claimedClean: boolean; source: string; capturedAt: string; evidenceNote?: string }>>().notNull().default([]),
  titleState: text("title_state").notNull().default("UNKNOWN"),
  parsedIssues: jsonb("parsed_issues").$type<Array<{ category: string; snippet: string; confidence: number }>>().notNull().default([]),
  redFlags: jsonb("red_flags").$type<Array<{ code: string; description: string; detectedAt: string }>>().notNull().default([]),
  postedAt: timestamp("posted_at", { withTimezone: true }),
  firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).notNull().defaultNow(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(),
  dedupKey: text("dedup_key").notNull(),
  workflowStage: text("workflow_stage").notNull().default("FOUND"),
  workflowHistory: jsonb("workflow_history").$type<Array<{ from: string; to: string; at: string; actor: string; note?: string }>>().notNull().default([]),
  watched: boolean("watched").notNull().default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const valuations = pgTable("valuations", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: text("owner_id").notNull().default("primary"),
  listingId: uuid("listing_id").notNull().references(() => listings.id, { onDelete: "cascade" }),
  provider: text("provider").notNull(),
  referenceGoodValue: numeric("reference_good_value", { precision: 10, scale: 2 }).notNull(),
  compMedian: numeric("comp_median", { precision: 10, scale: 2 }),
  compRangeLow: numeric("comp_range_low", { precision: 10, scale: 2 }),
  compRangeHigh: numeric("comp_range_high", { precision: 10, scale: 2 }),
  confidence: numeric("confidence", { precision: 4, scale: 3 }).notNull().default("0.800"),
  notes: text("notes"),
  enteredBy: text("entered_by").notNull().default("user"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const historyChecks = pgTable("history_checks", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: text("owner_id").notNull().default("primary"),
  listingId: uuid("listing_id").notNull().references(() => listings.id, { onDelete: "cascade" }),
  provider: text("provider").notNull(),
  vin: text("vin").notNull(),
  titleState: text("title_state").notNull(),
  brands: jsonb("brands").$type<string[]>().notNull().default([]),
  accidentCount: integer("accident_count"),
  odometerReadings: jsonb("odometer_readings").$type<number[]>().notNull().default([]),
  raw: jsonb("raw"),
  checkedAt: timestamp("checked_at", { withTimezone: true }).notNull().defaultNow(),
});

export const userIssues = pgTable("user_issues", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: text("owner_id").notNull().default("primary"),
  listingId: uuid("listing_id").notNull().references(() => listings.id, { onDelete: "cascade" }),
  category: text("category").notNull(),
  description: text("description").notNull(),
  severity: text("severity").notNull(),
  confidence: numeric("confidence", { precision: 4, scale: 3 }).notNull().default("0.900"),
  estimateLow: numeric("estimate_low", { precision: 10, scale: 2 }).notNull(),
  estimateExpected: numeric("estimate_expected", { precision: 10, scale: 2 }).notNull(),
  estimateHigh: numeric("estimate_high", { precision: 10, scale: 2 }).notNull(),
  majorRisk: boolean("major_risk").notNull().default(false),
  source: text("source").notNull().default("USER_INPUT"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const evaluations = pgTable("evaluations", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: text("owner_id").notNull().default("primary"),
  listingId: uuid("listing_id").notNull().references(() => listings.id, { onDelete: "cascade" }),
  profileId: uuid("profile_id").references(() => searchProfiles.id, { onDelete: "set null" }),
  score: integer("score").notNull(),
  scoreClass: text("score_class").notNull(),
  formulaVersion: text("formula_version").notNull().default("deal-score-v1"),
  askingRatio: numeric("asking_ratio", { precision: 6, scale: 4 }),
  gateAPassed: boolean("gate_a_passed"),
  gateBPassed: boolean("gate_b_passed"),
  expectedMargin: numeric("expected_margin", { precision: 12, scale: 2 }),
  fraudRiskScore: integer("fraud_risk_score"),
  hardRejected: boolean("hard_rejected").notNull().default(false),
  payload: jsonb("payload").notNull(), // full DealEvaluation — auditable decision record
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const alerts = pgTable("alerts", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: text("owner_id").notNull().default("primary"),
  listingId: uuid("listing_id").notNull().references(() => listings.id, { onDelete: "cascade" }),
  evaluationId: uuid("evaluation_id").references(() => evaluations.id, { onDelete: "cascade" }),
  alertKey: text("alert_key").notNull(),
  payload: jsonb("payload").notNull(),
  delivered: boolean("delivered").notNull().default(false),
  deliveryStatus: text("delivery_status").notNull().default("PENDING"),
  deliveryAttempts: integer("delivery_attempts").notNull().default(0),
  deliveryError: text("delivery_error"),
  deliveredAt: timestamp("delivered_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({ alertKeyUnique: uniqueIndex("alerts_owner_key_unique").on(table.ownerId, table.alertKey) }));

export const outcomes = pgTable("outcomes", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: text("owner_id").notNull().default("primary"),
  listingId: uuid("listing_id").notNull().references(() => listings.id, { onDelete: "cascade" }),
  evaluationId: uuid("evaluation_id").references(() => evaluations.id, { onDelete: "set null" }),
  outcome: text("outcome").notNull(),
  notes: text("notes"),
  actualRepairs: numeric("actual_repairs", { precision: 10, scale: 2 }),
  actualFinishedValue: numeric("actual_finished_value", { precision: 10, scale: 2 }),
  actualAllIn: numeric("actual_all_in", { precision: 10, scale: 2 }),
  actualMargin: numeric("actual_margin", { precision: 10, scale: 2 }),
  soldPrice: numeric("sold_price", { precision: 10, scale: 2 }),
  predictionError: jsonb("prediction_error"),
  recordedAt: timestamp("recorded_at", { withTimezone: true }).notNull().defaultNow(),
});

export const vinCache = pgTable("vin_cache", {
  vin: text("vin").primaryKey(),
  decoded: jsonb("decoded").notNull(),
  fetchedAt: timestamp("fetched_at", { withTimezone: true }).notNull().defaultNow(),
});
